behaviors:
  TraverseTrack:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 0.001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.7
        demo_path: Demos/
    behavioral_cloning:
      strength: 0.3
      demo_path: Demos/
    max_steps: 15000000
    time_horizon: 64
    summary_freq: 10000
    